variables:
  CI_REGISTRY:
    value: "gitregistry.knut.univention.de"
    description: "URI for GitLab CI Container Registry"

include:
  - project: univention/infrastructure/docker-services
    file:
      - pre-commit.yml

stages:
  - .pre
  - prepare
  - release
  - publish

.publish-common:
  artifacts:
    paths:
      - univention-ucs_modules-*
    expire_in: 14 days
  before_script:
    # Check if release has to be build
    - if [ -z "$RELEASE_VERSION" ]; then exit 0; fi
    # Set new semantic-release version
    - if [[ ${CI_COMMIT_BRANCH} != "main" ]];
      then
        VERSION=${RELEASE_VERSION}-dev${CI_PIPELINE_IID};
      else
        VERSION=${RELEASE_VERSION};
      fi
    - sed -i "/version. \"[0-9]\.[0-9]\.[0-9]\"/s/[0-9]\.[0-9]\.[0-9]/$VERSION/" galaxy.yml
  image: docker-registry.knut.univention.de/knut/ansible:latest
  script:
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --api-key ${ANSIBLE_GALAXY_API_KEY} univention-ucs_modules-${VERSION}.tar.gz
  stage: publish
  variables:
    GIT_DEPTH: "1"

.common-semantic-release:
  except:
    - triggers
    - tags
  image: docker-registry.knut.univention.de/knut/semantic-release:main
  stage: prepare
  variables:
    GIT_STRATEGY: clone

prepare:
  artifacts:
    reports:
      dotenv: ${CI_PROJECT_DIR}/deploy.env
  extends: .common-semantic-release
  script:
    - echo RELEASE_VERSION=$(semantic-release --dry-run --branches $CI_COMMIT_REF_NAME --plugins "@semantic-release/gitlab" | grep -oP "Published release [0-9]+\.[0-9]+\.[0-9]+ on" | grep -oP "[0-9]+\.[0-9]+\.[0-9]+") > ${CI_PROJECT_DIR}/deploy.env
    - cat ${CI_PROJECT_DIR}/deploy.env
  stage: prepare


pre-commit:
  stage: prepare
  extends: .pre-commit

release:
  artifacts:
    paths:
      - CHANGELOG.md
  extends: .common-semantic-release
  only:
    - main
  script:
    - |
      if test -f "${CI_PROJECT_DIR}/.releaserc"
      then
        PLUGINS=
      else
        PLUGINS="--plugins @semantic-release/gitlab,@semantic-release/release-notes-generator,@semantic-release/changelog"
      fi
    - semantic-release --branches $CI_COMMIT_REF_NAME $PLUGINS
  stage: release

publish-main:
  extends: .publish-common
  only:
    - main

publish-mr:
  except:
    - main
    - tags
  extends: .publish-common
  when: manual
