variables:
  CI_REGISTRY:
    value: "gitregistry.knut.univention.de"
    description: "URI for GitLab CI Container Registry"
  ENV_CFG:
    value: "${CI_PROJECT_DIR}/_test-environment/small-env.cfg"
    description: "Path to the config file for kvm_create. Example: ${CI_PROJECT_DIR}/_test-environment/small-env.cfg"
  TDP_VERSION:
    value: &TDP_VERSION "v8.2.0"
    description: "Version of the test dev pipeline. Example: v6.1.1"
  KVM_USER:
    value: "build"
    description: "user to connect to KVM host. Also used to prefix the host"
  KVM_BUILD_SERVER:
    value: "tross.knut.univention.de"
    description: "which KVM host?"
  UCS_VERSION:
    value: "5.2-6"
    description: "Version of the UCS image"

include:
  - project: univention/infrastructure/docker-services
    file:
      - pre-commit.yml
  - project: univention/prof-services/internal/devops/test-dev-pipeline
    ref: *TDP_VERSION
    file:
      - jobs-library.yml

stages:
  - .pre
  - deploy
  - prepare
  - release
  - publish

.publish-common:
  artifacts:
    paths:
      - univention-ucs_modules-*
    expire_in: 14 days
  before_script:
    # Check if release has to be build
    - if [ -z "$RELEASE_VERSION" ]; then exit 0; fi
    # Set new semantic-release version
    - if [[ ${CI_COMMIT_BRANCH} != "main" ]];
      then
        VERSION=${RELEASE_VERSION}-dev${CI_PIPELINE_IID};
      else
        VERSION=${RELEASE_VERSION};
      fi
    - sed -i "/version. \"[0-9]\.[0-9]\.[0-9]\"/s/[0-9]\.[0-9]\.[0-9]/$VERSION/" galaxy.yml
  image: docker-registry.knut.univention.de/knut/ansible:latest
  script:
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --api-key ${ANSIBLE_GALAXY_API_KEY} univention-ucs_modules-${VERSION}.tar.gz
  stage: publish
  variables:
    GIT_DEPTH: "1"

.common-semantic-release:
  except:
    - triggers
    - tags
  image: docker-registry.knut.univention.de/knut/semantic-release:main
  stage: prepare
  variables:
    GIT_STRATEGY: clone

prepare:
  artifacts:
    reports:
      dotenv: ${CI_PROJECT_DIR}/deploy.env
  extends: .common-semantic-release
  script:
    - echo RELEASE_VERSION=$(semantic-release --dry-run --branches $CI_COMMIT_REF_NAME --plugins "@semantic-release/gitlab" | grep -oP "Published release [0-9]+\.[0-9]+\.[0-9]+ on" | grep -oP "[0-9]+\.[0-9]+\.[0-9]+") > ${CI_PROJECT_DIR}/deploy.env
    - cat ${CI_PROJECT_DIR}/deploy.env
  stage: prepare


pre-commit:
  stage: prepare
  extends: .pre-commit

release:
  artifacts:
    paths:
      - CHANGELOG.md
  extends: .common-semantic-release
  only:
    - main
  script:
    - |
      if test -f "${CI_PROJECT_DIR}/.releaserc"
      then
        PLUGINS=
      else
        PLUGINS="--plugins @semantic-release/gitlab,@semantic-release/release-notes-generator,@semantic-release/changelog"
      fi
    - semantic-release --branches $CI_COMMIT_REF_NAME $PLUGINS
  stage: release

publish-main:
  extends: .publish-common
  only:
    - main

publish-mr:
  except:
    - main
    - tags
  extends: .publish-common
  when: manual


create_vms:
  stage: deploy
  extends: .tdp_create_vms
  # needed for win
  before_script:
    - apt update
    - apt install --yes nmap
    - !reference [.tdp_create_vms, before_script]
  # This can run immediatly therefore empty needs to skip stage order
  needs: []
  environment:
    name: test/${CI_COMMIT_REF_SLUG}
    on_stop: terminate_deployment
  artifacts:
    when: always
  variables:
    # This is passed on as `kvm_extra_label` to `ucs-kvm-create`
    JOB_BASE_NAME: "${TEST_ENV_EXTRA_LABEL}_${CI_COMMIT_REF_SLUG}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
      variables:
        HAS_BUILT_PACKAGES: "true"
    # - if: *PUSH_TO_DEFAULT_BRANCH
    #   when: never

terminate_deployment:
  stage: deploy
  extends: .tdp_stop_deployment
  environment:
    name: test/${CI_COMMIT_REF_SLUG}
  needs:
    - job: create_vms
      optional: true
  rules:
    # - if: *PUSH_TO_DEFAULT_BRANCH
    #   when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
      when: manual

# ansible-test-sanity:
#   stage: test
