---
server_type: "master"

# Description: The system DNS domain name
hostname_domain: "{{ inventory_hostname | replace(inventory_hostname_short + '.', '') }}"
# Description: The systems host name.
hostname: "{{ inventory_hostname_short }}"

# Packages
custom_packages:
  - "htop"
